INSERT INTO PRODUCT (AVAILABILITY, BRAND, CATEGORY, DESCRIPTION, NAME, PRICE, QUANTITY, RELEASE_DATE)
VALUES  (1, 'BrandA', 'Electronics', 'A high-quality smartphone', 'Smartphone X', 699.99, 50, '2023-09-15');


INSERT INTO PRODUCT (AVAILABILITY, BRAND, CATEGORY, DESCRIPTION, NAME, PRICE, QUANTITY, RELEASE_DATE)
VALUES  (0, 'BrandB', 'Home Appliances', 'A powerful vacuum cleaner', 'VacuumPro 3000', 299.99, 0, '2024-01-05');


INSERT INTO PRODUCT (AVAILABILITY, BRAND, CATEGORY, DESCRIPTION, NAME, PRICE, QUANTITY, RELEASE_DATE)
VALUES  (1, 'BrandC', 'Furniture', 'A modern ergonomic chair', 'ErgoChair Deluxe', 199.99, 25, '2022-11-10');